language: ruby
cache: bundler
rvm:
  - 2.6.2
env:
  - DB=pgsql
services:
  - postgresql
before_install:
  - gem update --system
  - gem install -v 2.0.1 bundler --no-rdoc --no-ri
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database maintainer-seeker_test;' -U postgres
script:
  - RAILS_ENV=test bin/rails db:migrate --trace
  - bin/rails db:test:prepare
  - bin/rails test
