version: "3.6"
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#   app:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/maintainer-seeker
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  app: &app_base
    image: maintainer_seeker_app
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=${ADDITIONAL_PACKAGES}
        - EXECJS_RUNTIME=${EXECJS_RUNTIME}
        - RAILS_ENV=${RAILS_ENV}
    tty: true
    stdin_open: true
    env_file: .env
    ports:
      - "3000"
    links:
      - db
      - redis
    volumes:
      - .:/app

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - app

  webpacker:
    <<: *app_base
    command: yarn && ./bin/webpack-dev-server
    ports: ["3035:3035"]
    depends_on:
      - app

volumes:
  db-data:
